#Version of the Maven Wrapper being used.
#Wrapper is a tool that ensures everyone uses the same Maven version.
wrapperVersion=3.3.4

#This means it will only download and run Maven via script, not embed binaries.
#Keeps your project lightweight.
distributionType=only-script

#This is the actual Maven version (3.9.12) that will be downloaded and used.
#When you run: ./mvnw clean install
#it downloads this version automatically.
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.12/apache-maven-3.9.12-bin.zip

#✅ Why this is useful
#No need to install Maven manually
#Ensures same Maven version across all environments (local + CI/CD + Docker)
#Avoids version conflicts