# Production-specific settings
# These should be overridden by environment variables in production
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Production logging level
logging.level.root=WARN
logging.level.com.nirmaansetu.backend=INFO

# ELK Logstash Destination
logging.logstash.destination=${LOGSTASH_DESTINATION:localhost:5044}
