# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD:}

# JWT
jwt.secret=${JWT_SECRET}

# Encryption
app.encryption.secret-key=${ENCRYPTION_SECRET}

# Twilio
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}

# Logstash (Optional)
logging.logstash.destination=${LOGSTASH_DESTINATION:}

# Logging
logging.level.root=INFO
logging.level.com.nirmaansetu.backend=INFO